using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.stat.dist_
{
	/// <summary>
	/// a borel family generated by real intervals.
	/// </summary>
	public interface IBorel
	{

	}
}
